//! Include the file that gets generated by the build script invoking `w4 png2src`, etc.
//! It should be included in exactly this one file, and then used from here.

include!(concat!(env!("OUT_DIR"), "/assets.rs"));

pub mod cursor;
pub mod item;
