use crate::audio::{Pattern, Sfx, Tone};

pub const SFX_DATA: &[Sfx] = &[
    Sfx {
        frames_per_tone: 8,
        loop_restart: None,
        tones: &[
            Tone {
                frequency: 493,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 493,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 493,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 493,
                duration: 8,
                volume: 0,
                flags: 2,
            },
            Tone {
                frequency: 493,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 493,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 493,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 493,
                duration: 8,
                volume: 0,
                flags: 2,
            },
            Tone {
                frequency: 523,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 523,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 523,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 65,
                duration: 8,
                volume: 0,
                flags: 2,
            },
            Tone {
                frequency: 587,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 587,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 587,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 65,
                duration: 8,
                volume: 0,
                flags: 2,
            },
            Tone {
                frequency: 587,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 587,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 587,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 65,
                duration: 8,
                volume: 0,
                flags: 2,
            },
            Tone {
                frequency: 523,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 523,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 523,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 65,
                duration: 8,
                volume: 0,
                flags: 2,
            },
            Tone {
                frequency: 493,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 493,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 493,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 65,
                duration: 8,
                volume: 0,
                flags: 2,
            },
            Tone {
                frequency: 440,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 440,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 440,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 65,
                duration: 8,
                volume: 0,
                flags: 2,
            },
        ],
    },
    Sfx {
        frames_per_tone: 8,
        loop_restart: None,
        tones: &[
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 0,
                flags: 2,
            },
            Tone {
                frequency: 184,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 184,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 184,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 184,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 184,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 184,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 184,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 184,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 184,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 184,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 184,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 184,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 184,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 184,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 184,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 174,
                duration: 8,
                volume: 0,
                flags: 2,
            },
        ],
    },
    Sfx {
        frames_per_tone: 8,
        loop_restart: None,
        tones: &[
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 0,
                flags: 2,
            },
            Tone {
                frequency: 220,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 220,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 220,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 220,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 220,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 220,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 220,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 220,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 220,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 220,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 220,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 220,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 220,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 220,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 220,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 220,
                duration: 8,
                volume: 0,
                flags: 2,
            },
        ],
    },
    Sfx {
        frames_per_tone: 8,
        loop_restart: None,
        tones: &[
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 0,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 0,
                flags: 2,
            },
        ],
    },
    Sfx {
        frames_per_tone: 8,
        loop_restart: None,
        tones: &[
            Tone {
                frequency: 391,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 391,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 391,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 493,
                duration: 8,
                volume: 0,
                flags: 2,
            },
            Tone {
                frequency: 391,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 391,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 391,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 440,
                duration: 8,
                volume: 0,
                flags: 2,
            },
            Tone {
                frequency: 440,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 440,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 440,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 440,
                duration: 8,
                volume: 0,
                flags: 2,
            },
            Tone {
                frequency: 493,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 493,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 493,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 65,
                duration: 8,
                volume: 0,
                flags: 2,
            },
            Tone {
                frequency: 493,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 493,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 493,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 493,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 493,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 65,
                duration: 8,
                volume: 0,
                flags: 2,
            },
            Tone {
                frequency: 440,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 65,
                duration: 8,
                volume: 0,
                flags: 2,
            },
            Tone {
                frequency: 440,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 440,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 440,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 440,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 440,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 440,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 440,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 65,
                duration: 8,
                volume: 0,
                flags: 2,
            },
        ],
    },
    Sfx {
        frames_per_tone: 8,
        loop_restart: None,
        tones: &[
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 0,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 174,
                duration: 8,
                volume: 0,
                flags: 2,
            },
            Tone {
                frequency: 184,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 184,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 184,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 184,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 184,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 184,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 184,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 65,
                duration: 8,
                volume: 0,
                flags: 2,
            },
        ],
    },
    Sfx {
        frames_per_tone: 8,
        loop_restart: None,
        tones: &[
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 0,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 220,
                duration: 8,
                volume: 0,
                flags: 2,
            },
            Tone {
                frequency: 220,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 220,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 220,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 220,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 220,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 220,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 220,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 65,
                duration: 8,
                volume: 0,
                flags: 2,
            },
        ],
    },
    Sfx {
        frames_per_tone: 8,
        loop_restart: None,
        tones: &[
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 0,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 0,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 0,
                flags: 2,
            },
        ],
    },
    Sfx {
        frames_per_tone: 8,
        loop_restart: None,
        tones: &[
            Tone {
                frequency: 391,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 391,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 391,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 493,
                duration: 8,
                volume: 0,
                flags: 2,
            },
            Tone {
                frequency: 391,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 391,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 391,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 440,
                duration: 8,
                volume: 0,
                flags: 2,
            },
            Tone {
                frequency: 440,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 440,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 440,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 440,
                duration: 8,
                volume: 0,
                flags: 2,
            },
            Tone {
                frequency: 493,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 493,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 493,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 65,
                duration: 8,
                volume: 0,
                flags: 2,
            },
            Tone {
                frequency: 440,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 440,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 440,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 440,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 440,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 65,
                duration: 8,
                volume: 0,
                flags: 2,
            },
            Tone {
                frequency: 391,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 65,
                duration: 8,
                volume: 0,
                flags: 2,
            },
            Tone {
                frequency: 391,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 391,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 391,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 391,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 391,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 391,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 391,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 65,
                duration: 8,
                volume: 0,
                flags: 2,
            },
        ],
    },
    Sfx {
        frames_per_tone: 8,
        loop_restart: None,
        tones: &[
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 65,
                duration: 8,
                volume: 0,
                flags: 2,
            },
            Tone {
                frequency: 184,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 184,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 184,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 184,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 184,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 184,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 184,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 174,
                duration: 8,
                volume: 0,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 195,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 65,
                duration: 8,
                volume: 0,
                flags: 2,
            },
        ],
    },
    Sfx {
        frames_per_tone: 8,
        loop_restart: None,
        tones: &[
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 65,
                duration: 8,
                volume: 0,
                flags: 2,
            },
            Tone {
                frequency: 220,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 220,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 220,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 220,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 220,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 220,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 220,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 65,
                duration: 8,
                volume: 0,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 246,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 65,
                duration: 8,
                volume: 0,
                flags: 2,
            },
        ],
    },
    Sfx {
        frames_per_tone: 8,
        loop_restart: None,
        tones: &[
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 65,
                duration: 8,
                volume: 0,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 65,
                duration: 8,
                volume: 0,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 293,
                duration: 8,
                volume: 71,
                flags: 2,
            },
            Tone {
                frequency: 65,
                duration: 8,
                volume: 0,
                flags: 2,
            },
        ],
    },
];

pub const MUSIC_DATA: &[Pattern] = &[
    Pattern {
        loop_start: false,
        loop_back: false,
        stop_at_end: false,
        sfxes: &[&SFX_DATA[0]],
    },
    Pattern {
        loop_start: false,
        loop_back: false,
        stop_at_end: false,
        sfxes: &[&SFX_DATA[4]],
    },
    Pattern {
        loop_start: false,
        loop_back: false,
        stop_at_end: false,
        sfxes: &[&SFX_DATA[0]],
    },
    Pattern {
        loop_start: false,
        loop_back: false,
        stop_at_end: true,
        sfxes: &[&SFX_DATA[8]],
    },
];
